# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

services:
  bonus-service:
    name: bonus-service
    container: cr.yandex/crp3lvholiifmsf14j67/bonus-service
    replicaCount: 1
    env:
      DB_DSN: "host=db-service user=postgres password=password dbname=bonusdb port=5432" # add on deploy like ""
    publishUrl: /bonus-service-direct/
    port: 8050
    targetPort: 8050
  flight-service:
    name: flight-service
    container: cr.yandex/crp3lvholiifmsf14j67/flight-service
    replicaCount: 1
    env:
      DB_DSN: "host=db-service user=postgres password=password dbname=flightdb port=5432" # add on deploy
    publishUrl: /flight-service-direct/
    port: 8060
    targetPort: 8060
  ticket-service:
    name: ticket-service
    container: cr.yandex/crp3lvholiifmsf14j67/ticket-service
    replicaCount: 1
    env:
      DB_DSN: "host=db-service user=postgres password=password dbname=ticketdb port=5432" # add on deploy
    publishUrl: /ticket-service-direct/
    port: 8070
    targetPort: 8070
  gateway-service:
    name: gateway-service
    container: cr.yandex/crp3lvholiifmsf14j67/gateway-service
    replicaCount: 1
    env:
      BONUS_SERVICE_URL: "http://bonus-service/api/v1/"
      FLIGHT_SERVICE_URL: "http://flight-service/api/v1/"
      TICKET_SERVICE_URL: "http://ticket-service/api/v1/"
    publishUrl: /
    port: 8080
    targetPort: 8080