version: '3.1'

services:
  bonus-database:
    image: postgres:16-alpine
    container_name: bonus-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bonus_db
    volumes:
      - ./pg_data_bonus:/var/lib/postgresql/data
      - ./bonus_service/sql/init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 15s
      retries: 10

  flight-database:
    image: postgres:16-alpine
    container_name: flight-database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flight_db
    volumes:
      - ./pg_data_flight:/var/lib/postgresql/data
      - ./flight_service/sql/init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 15s
      retries: 10

  ticket-database:
    image: postgres:16-alpine
    container_name: ticket-database
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticket_db
    volumes:
      - ./pg_data_ticket:/var/lib/postgresql/data
      - ./ticket_service/sql/init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 15s
      retries: 10

  bonus-service:
    image: cr.yandex/catahd5f79892d74b3i5/bonus-service
    container_name: bonus-service
    build:
      context: "."
      dockerfile: ./docker/bonus.Dockerfile
    ports:
      - "8050:8050"
    networks:
      - default
    depends_on:
      bonus-database:
        condition: service_healthy

  flight-service:
    image: cr.yandex/catahd5f79892d74b3i5/flight-service
    container_name: flight-service
    build:
      context: "."
      dockerfile: ./docker/flight.Dockerfile
    ports:
      - "8060:8060"
    networks:
      - default
    depends_on:
      flight-database:
        condition: service_healthy

  ticket-service:
    image: cr.yandex/catahd5f79892d74b3i5/ticket-service
    container_name: ticket-service
    build:
      context: "."
      dockerfile: ./docker/ticket.Dockerfile
    ports:
      - "8070:8070"
    networks:
      - default
    depends_on:
      ticket-database:
        condition: service_healthy

  gateway-service:
    image: cr.yandex/catahd5f79892d74b3i5/gateway-service
    container_name: gateway-service
    build:
      context: "."
      dockerfile: ./docker/gateway.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default

volumes:
  pg_data_bonus:
    driver: local
  pg_data_flight:
    driver: local
  pg_data_ticket:
    driver: local

networks:
  default:
